spring:
  # MySQL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/webdb4
    username: ${DATASOURCE_ID}
    password: ${DATASOURCE_PW}
  # JPA
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

# Log4j2
logging:
  level:
    com.springframework: info
    com.springframework.security: debug
    com.webdev: debug

# jwt secret key
com:
  webdev:
    jwt:
      secret: ${JWT_SECRET}